// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_profile.proto

package com.snapchat.targeting.proto;

public final class UserProfileProto {
  private UserProfileProto() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public interface UserProfileOrBuilder
      extends
      // @@protoc_insertion_point(interface_extends:com.snapchat.targeting.proto.UserProfile)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 latest_timestamp_millis = 8;</code>
     *
     * @return The latestTimestampMillis.
     */
    long getLatestTimestampMillis();

    /**
     *
     *
     * <pre>
     * The following three ids are not persisted in BT and it's used for joining only!
     * </pre>
     *
     * <code>string user_id = 7;</code>
     *
     * @return The userId.
     */
    java.lang.String getUserId();
    /**
     *
     *
     * <pre>
     * The following three ids are not persisted in BT and it's used for joining only!
     * </pre>
     *
     * <code>string user_id = 7;</code>
     *
     * @return The bytes for userId.
     */
    com.google.protobuf.ByteString getUserIdBytes();

    /**
     * <code>string user_name = 11;</code>
     *
     * @return The userName.
     */
    java.lang.String getUserName();
    /**
     * <code>string user_name = 11;</code>
     *
     * @return The bytes for userName.
     */
    com.google.protobuf.ByteString getUserNameBytes();

    /**
     * <code>string ghost_id = 21;</code>
     *
     * @return The ghostId.
     */
    java.lang.String getGhostId();
    /**
     * <code>string ghost_id = 21;</code>
     *
     * @return The bytes for ghostId.
     */
    com.google.protobuf.ByteString getGhostIdBytes();

    /**
     * <code>string said = 16;</code>
     *
     * @return The said.
     */
    java.lang.String getSaid();
    /**
     * <code>string said = 16;</code>
     *
     * @return The bytes for said.
     */
    com.google.protobuf.ByteString getSaidBytes();

    /** <code>map&lt;string, string&gt; supplement = 17;</code> */
    int getSupplementCount();
    /** <code>map&lt;string, string&gt; supplement = 17;</code> */
    boolean containsSupplement(java.lang.String key);
    /** Use {@link #getSupplementMap()} instead. */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String> getSupplement();
    /** <code>map&lt;string, string&gt; supplement = 17;</code> */
    java.util.Map<java.lang.String, java.lang.String> getSupplementMap();
    /** <code>map&lt;string, string&gt; supplement = 17;</code> */
    java.lang.String getSupplementOrDefault(java.lang.String key, java.lang.String defaultValue);
    /** <code>map&lt;string, string&gt; supplement = 17;</code> */
    java.lang.String getSupplementOrThrow(java.lang.String key);

    /**
     * <code>repeated int64 installed_hashed_app_ids = 23;</code>
     *
     * @return A list containing the installedHashedAppIds.
     */
    java.util.List<java.lang.Long> getInstalledHashedAppIdsList();
    /**
     * <code>repeated int64 installed_hashed_app_ids = 23;</code>
     *
     * @return The count of installedHashedAppIds.
     */
    int getInstalledHashedAppIdsCount();
    /**
     * <code>repeated int64 installed_hashed_app_ids = 23;</code>
     *
     * @param index The index of the element to return.
     * @return The installedHashedAppIds at the given index.
     */
    long getInstalledHashedAppIds(int index);
  }
  /**
   *
   *
   * <pre>
   * next one is 27
   * </pre>
   *
   * Protobuf type {@code com.snapchat.targeting.proto.UserProfile}
   */
  public static final class UserProfile extends com.google.protobuf.GeneratedMessageV3
      implements
      // @@protoc_insertion_point(message_implements:com.snapchat.targeting.proto.UserProfile)
      UserProfileOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use UserProfile.newBuilder() to construct.
    private UserProfile(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private UserProfile() {
      userId_ = "";
      userName_ = "";
      ghostId_ = "";
      said_ = "";
      installedHashedAppIds_ = emptyLongList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
      return new UserProfile();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
      return this.unknownFields;
    }

    private UserProfile(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 58:
              {
                java.lang.String s = input.readStringRequireUtf8();

                userId_ = s;
                break;
              }
            case 64:
              {
                latestTimestampMillis_ = input.readInt64();
                break;
              }
            case 90:
              {
                java.lang.String s = input.readStringRequireUtf8();

                userName_ = s;
                break;
              }
            case 130:
              {
                java.lang.String s = input.readStringRequireUtf8();

                said_ = s;
                break;
              }
            case 138:
              {
                if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                  supplement_ =
                      com.google.protobuf.MapField.newMapField(
                          SupplementDefaultEntryHolder.defaultEntry);
                  mutable_bitField0_ |= 0x00000001;
                }
                com.google.protobuf.MapEntry<java.lang.String, java.lang.String> supplement__ =
                    input.readMessage(
                        SupplementDefaultEntryHolder.defaultEntry.getParserForType(),
                        extensionRegistry);
                supplement_.getMutableMap().put(supplement__.getKey(), supplement__.getValue());
                break;
              }
            case 170:
              {
                java.lang.String s = input.readStringRequireUtf8();

                ghostId_ = s;
                break;
              }
            case 184:
              {
                if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                  installedHashedAppIds_ = newLongList();
                  mutable_bitField0_ |= 0x00000002;
                }
                installedHashedAppIds_.addLong(input.readInt64());
                break;
              }
            case 186:
              {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                if (!((mutable_bitField0_ & 0x00000002) != 0) && input.getBytesUntilLimit() > 0) {
                  installedHashedAppIds_ = newLongList();
                  mutable_bitField0_ |= 0x00000002;
                }
                while (input.getBytesUntilLimit() > 0) {
                  installedHashedAppIds_.addLong(input.readInt64());
                }
                input.popLimit(limit);
                break;
              }
            default:
              {
                if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          installedHashedAppIds_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.snapchat.targeting.proto.UserProfileProto
          .internal_static_com_snapchat_targeting_proto_UserProfile_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(int number) {
      switch (number) {
        case 17:
          return internalGetSupplement();
        default:
          throw new RuntimeException("Invalid map field number: " + number);
      }
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.snapchat.targeting.proto.UserProfileProto
          .internal_static_com_snapchat_targeting_proto_UserProfile_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.snapchat.targeting.proto.UserProfileProto.UserProfile.class,
              com.snapchat.targeting.proto.UserProfileProto.UserProfile.Builder.class);
    }

    public static final int LATEST_TIMESTAMP_MILLIS_FIELD_NUMBER = 8;
    private long latestTimestampMillis_;
    /**
     * <code>int64 latest_timestamp_millis = 8;</code>
     *
     * @return The latestTimestampMillis.
     */
    public long getLatestTimestampMillis() {
      return latestTimestampMillis_;
    }

    public static final int USER_ID_FIELD_NUMBER = 7;
    private volatile java.lang.Object userId_;
    /**
     *
     *
     * <pre>
     * The following three ids are not persisted in BT and it's used for joining only!
     * </pre>
     *
     * <code>string user_id = 7;</code>
     *
     * @return The userId.
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     *
     *
     * <pre>
     * The following three ids are not persisted in BT and it's used for joining only!
     * </pre>
     *
     * <code>string user_id = 7;</code>
     *
     * @return The bytes for userId.
     */
    public com.google.protobuf.ByteString getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_NAME_FIELD_NUMBER = 11;
    private volatile java.lang.Object userName_;
    /**
     * <code>string user_name = 11;</code>
     *
     * @return The userName.
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      }
    }
    /**
     * <code>string user_name = 11;</code>
     *
     * @return The bytes for userName.
     */
    public com.google.protobuf.ByteString getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GHOST_ID_FIELD_NUMBER = 21;
    private volatile java.lang.Object ghostId_;
    /**
     * <code>string ghost_id = 21;</code>
     *
     * @return The ghostId.
     */
    public java.lang.String getGhostId() {
      java.lang.Object ref = ghostId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ghostId_ = s;
        return s;
      }
    }
    /**
     * <code>string ghost_id = 21;</code>
     *
     * @return The bytes for ghostId.
     */
    public com.google.protobuf.ByteString getGhostIdBytes() {
      java.lang.Object ref = ghostId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        ghostId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SAID_FIELD_NUMBER = 16;
    private volatile java.lang.Object said_;
    /**
     * <code>string said = 16;</code>
     *
     * @return The said.
     */
    public java.lang.String getSaid() {
      java.lang.Object ref = said_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        said_ = s;
        return s;
      }
    }
    /**
     * <code>string said = 16;</code>
     *
     * @return The bytes for said.
     */
    public com.google.protobuf.ByteString getSaidBytes() {
      java.lang.Object ref = said_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        said_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUPPLEMENT_FIELD_NUMBER = 17;

    private static final class SupplementDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<java.lang.String, java.lang.String> defaultEntry =
          com.google.protobuf.MapEntry.<java.lang.String, java.lang.String>newDefaultInstance(
              com.snapchat.targeting.proto.UserProfileProto
                  .internal_static_com_snapchat_targeting_proto_UserProfile_SupplementEntry_descriptor,
              com.google.protobuf.WireFormat.FieldType.STRING,
              "",
              com.google.protobuf.WireFormat.FieldType.STRING,
              "");
    }

    private com.google.protobuf.MapField<java.lang.String, java.lang.String> supplement_;

    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetSupplement() {
      if (supplement_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            SupplementDefaultEntryHolder.defaultEntry);
      }
      return supplement_;
    }

    public int getSupplementCount() {
      return internalGetSupplement().getMap().size();
    }
    /** <code>map&lt;string, string&gt; supplement = 17;</code> */
    public boolean containsSupplement(java.lang.String key) {
      if (key == null) {
        throw new java.lang.NullPointerException();
      }
      return internalGetSupplement().getMap().containsKey(key);
    }
    /** Use {@link #getSupplementMap()} instead. */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getSupplement() {
      return getSupplementMap();
    }
    /** <code>map&lt;string, string&gt; supplement = 17;</code> */
    public java.util.Map<java.lang.String, java.lang.String> getSupplementMap() {
      return internalGetSupplement().getMap();
    }
    /** <code>map&lt;string, string&gt; supplement = 17;</code> */
    public java.lang.String getSupplementOrDefault(
        java.lang.String key, java.lang.String defaultValue) {
      if (key == null) {
        throw new java.lang.NullPointerException();
      }
      java.util.Map<java.lang.String, java.lang.String> map = internalGetSupplement().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /** <code>map&lt;string, string&gt; supplement = 17;</code> */
    public java.lang.String getSupplementOrThrow(java.lang.String key) {
      if (key == null) {
        throw new java.lang.NullPointerException();
      }
      java.util.Map<java.lang.String, java.lang.String> map = internalGetSupplement().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int INSTALLED_HASHED_APP_IDS_FIELD_NUMBER = 23;
    private com.google.protobuf.Internal.LongList installedHashedAppIds_;
    /**
     * <code>repeated int64 installed_hashed_app_ids = 23;</code>
     *
     * @return A list containing the installedHashedAppIds.
     */
    public java.util.List<java.lang.Long> getInstalledHashedAppIdsList() {
      return installedHashedAppIds_;
    }
    /**
     * <code>repeated int64 installed_hashed_app_ids = 23;</code>
     *
     * @return The count of installedHashedAppIds.
     */
    public int getInstalledHashedAppIdsCount() {
      return installedHashedAppIds_.size();
    }
    /**
     * <code>repeated int64 installed_hashed_app_ids = 23;</code>
     *
     * @param index The index of the element to return.
     * @return The installedHashedAppIds at the given index.
     */
    public long getInstalledHashedAppIds(int index) {
      return installedHashedAppIds_.getLong(index);
    }

    private int installedHashedAppIdsMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
      getSerializedSize();
      if (!getUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, userId_);
      }
      if (latestTimestampMillis_ != 0L) {
        output.writeInt64(8, latestTimestampMillis_);
      }
      if (!getUserNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, userName_);
      }
      if (!getSaidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 16, said_);
      }
      com.google.protobuf.GeneratedMessageV3.serializeStringMapTo(
          output, internalGetSupplement(), SupplementDefaultEntryHolder.defaultEntry, 17);
      if (!getGhostIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 21, ghostId_);
      }
      if (getInstalledHashedAppIdsList().size() > 0) {
        output.writeUInt32NoTag(186);
        output.writeUInt32NoTag(installedHashedAppIdsMemoizedSerializedSize);
      }
      for (int i = 0; i < installedHashedAppIds_.size(); i++) {
        output.writeInt64NoTag(installedHashedAppIds_.getLong(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, userId_);
      }
      if (latestTimestampMillis_ != 0L) {
        size += com.google.protobuf.CodedOutputStream.computeInt64Size(8, latestTimestampMillis_);
      }
      if (!getUserNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, userName_);
      }
      if (!getSaidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, said_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry :
          internalGetSupplement().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String> supplement__ =
            SupplementDefaultEntryHolder.defaultEntry
                .newBuilderForType()
                .setKey(entry.getKey())
                .setValue(entry.getValue())
                .build();
        size += com.google.protobuf.CodedOutputStream.computeMessageSize(17, supplement__);
      }
      if (!getGhostIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(21, ghostId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < installedHashedAppIds_.size(); i++) {
          dataSize +=
              com.google.protobuf.CodedOutputStream.computeInt64SizeNoTag(
                  installedHashedAppIds_.getLong(i));
        }
        size += dataSize;
        if (!getInstalledHashedAppIdsList().isEmpty()) {
          size += 2;
          size += com.google.protobuf.CodedOutputStream.computeInt32SizeNoTag(dataSize);
        }
        installedHashedAppIdsMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof com.snapchat.targeting.proto.UserProfileProto.UserProfile)) {
        return super.equals(obj);
      }
      com.snapchat.targeting.proto.UserProfileProto.UserProfile other =
          (com.snapchat.targeting.proto.UserProfileProto.UserProfile) obj;

      if (getLatestTimestampMillis() != other.getLatestTimestampMillis()) return false;
      if (!getUserId().equals(other.getUserId())) return false;
      if (!getUserName().equals(other.getUserName())) return false;
      if (!getGhostId().equals(other.getGhostId())) return false;
      if (!getSaid().equals(other.getSaid())) return false;
      if (!internalGetSupplement().equals(other.internalGetSupplement())) return false;
      if (!getInstalledHashedAppIdsList().equals(other.getInstalledHashedAppIdsList()))
        return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LATEST_TIMESTAMP_MILLIS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getLatestTimestampMillis());
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (37 * hash) + USER_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserName().hashCode();
      hash = (37 * hash) + GHOST_ID_FIELD_NUMBER;
      hash = (53 * hash) + getGhostId().hashCode();
      hash = (37 * hash) + SAID_FIELD_NUMBER;
      hash = (53 * hash) + getSaid().hashCode();
      if (!internalGetSupplement().getMap().isEmpty()) {
        hash = (37 * hash) + SUPPLEMENT_FIELD_NUMBER;
        hash = (53 * hash) + internalGetSupplement().hashCode();
      }
      if (getInstalledHashedAppIdsCount() > 0) {
        hash = (37 * hash) + INSTALLED_HASHED_APP_IDS_FIELD_NUMBER;
        hash = (53 * hash) + getInstalledHashedAppIdsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.snapchat.targeting.proto.UserProfileProto.UserProfile parseFrom(
        java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.snapchat.targeting.proto.UserProfileProto.UserProfile parseFrom(
        java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.snapchat.targeting.proto.UserProfileProto.UserProfile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.snapchat.targeting.proto.UserProfileProto.UserProfile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.snapchat.targeting.proto.UserProfileProto.UserProfile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.snapchat.targeting.proto.UserProfileProto.UserProfile parseFrom(
        byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.snapchat.targeting.proto.UserProfileProto.UserProfile parseFrom(
        java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.snapchat.targeting.proto.UserProfileProto.UserProfile parseFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static com.snapchat.targeting.proto.UserProfileProto.UserProfile parseDelimitedFrom(
        java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static com.snapchat.targeting.proto.UserProfileProto.UserProfile parseDelimitedFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static com.snapchat.targeting.proto.UserProfileProto.UserProfile parseFrom(
        com.google.protobuf.CodedInputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.snapchat.targeting.proto.UserProfileProto.UserProfile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
          PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(
        com.snapchat.targeting.proto.UserProfileProto.UserProfile prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     *
     *
     * <pre>
     * next one is 27
     * </pre>
     *
     * Protobuf type {@code com.snapchat.targeting.proto.UserProfile}
     */
    public static final class Builder
        extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
        implements
        // @@protoc_insertion_point(builder_implements:com.snapchat.targeting.proto.UserProfile)
        com.snapchat.targeting.proto.UserProfileProto.UserProfileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.snapchat.targeting.proto.UserProfileProto
            .internal_static_com_snapchat_targeting_proto_UserProfile_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(int number) {
        switch (number) {
          case 17:
            return internalGetSupplement();
          default:
            throw new RuntimeException("Invalid map field number: " + number);
        }
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(int number) {
        switch (number) {
          case 17:
            return internalGetMutableSupplement();
          default:
            throw new RuntimeException("Invalid map field number: " + number);
        }
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.snapchat.targeting.proto.UserProfileProto
            .internal_static_com_snapchat_targeting_proto_UserProfile_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.snapchat.targeting.proto.UserProfileProto.UserProfile.class,
                com.snapchat.targeting.proto.UserProfileProto.UserProfile.Builder.class);
      }

      // Construct using com.snapchat.targeting.proto.UserProfileProto.UserProfile.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {}
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        latestTimestampMillis_ = 0L;

        userId_ = "";

        userName_ = "";

        ghostId_ = "";

        said_ = "";

        internalGetMutableSupplement().clear();
        installedHashedAppIds_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return com.snapchat.targeting.proto.UserProfileProto
            .internal_static_com_snapchat_targeting_proto_UserProfile_descriptor;
      }

      @java.lang.Override
      public com.snapchat.targeting.proto.UserProfileProto.UserProfile getDefaultInstanceForType() {
        return com.snapchat.targeting.proto.UserProfileProto.UserProfile.getDefaultInstance();
      }

      @java.lang.Override
      public com.snapchat.targeting.proto.UserProfileProto.UserProfile build() {
        com.snapchat.targeting.proto.UserProfileProto.UserProfile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.snapchat.targeting.proto.UserProfileProto.UserProfile buildPartial() {
        com.snapchat.targeting.proto.UserProfileProto.UserProfile result =
            new com.snapchat.targeting.proto.UserProfileProto.UserProfile(this);
        int from_bitField0_ = bitField0_;
        result.latestTimestampMillis_ = latestTimestampMillis_;
        result.userId_ = userId_;
        result.userName_ = userName_;
        result.ghostId_ = ghostId_;
        result.said_ = said_;
        result.supplement_ = internalGetSupplement();
        result.supplement_.makeImmutable();
        if (((bitField0_ & 0x00000002) != 0)) {
          installedHashedAppIds_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.installedHashedAppIds_ = installedHashedAppIds_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index,
          java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.snapchat.targeting.proto.UserProfileProto.UserProfile) {
          return mergeFrom((com.snapchat.targeting.proto.UserProfileProto.UserProfile) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.snapchat.targeting.proto.UserProfileProto.UserProfile other) {
        if (other == com.snapchat.targeting.proto.UserProfileProto.UserProfile.getDefaultInstance())
          return this;
        if (other.getLatestTimestampMillis() != 0L) {
          setLatestTimestampMillis(other.getLatestTimestampMillis());
        }
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        if (!other.getUserName().isEmpty()) {
          userName_ = other.userName_;
          onChanged();
        }
        if (!other.getGhostId().isEmpty()) {
          ghostId_ = other.ghostId_;
          onChanged();
        }
        if (!other.getSaid().isEmpty()) {
          said_ = other.said_;
          onChanged();
        }
        internalGetMutableSupplement().mergeFrom(other.internalGetSupplement());
        if (!other.installedHashedAppIds_.isEmpty()) {
          if (installedHashedAppIds_.isEmpty()) {
            installedHashedAppIds_ = other.installedHashedAppIds_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureInstalledHashedAppIdsIsMutable();
            installedHashedAppIds_.addAll(other.installedHashedAppIds_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.snapchat.targeting.proto.UserProfileProto.UserProfile parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage =
              (com.snapchat.targeting.proto.UserProfileProto.UserProfile) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int bitField0_;

      private long latestTimestampMillis_;
      /**
       * <code>int64 latest_timestamp_millis = 8;</code>
       *
       * @return The latestTimestampMillis.
       */
      public long getLatestTimestampMillis() {
        return latestTimestampMillis_;
      }
      /**
       * <code>int64 latest_timestamp_millis = 8;</code>
       *
       * @param value The latestTimestampMillis to set.
       * @return This builder for chaining.
       */
      public Builder setLatestTimestampMillis(long value) {

        latestTimestampMillis_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 latest_timestamp_millis = 8;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearLatestTimestampMillis() {

        latestTimestampMillis_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object userId_ = "";
      /**
       *
       *
       * <pre>
       * The following three ids are not persisted in BT and it's used for joining only!
       * </pre>
       *
       * <code>string user_id = 7;</code>
       *
       * @return The userId.
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       *
       *
       * <pre>
       * The following three ids are not persisted in BT and it's used for joining only!
       * </pre>
       *
       * <code>string user_id = 7;</code>
       *
       * @return The bytes for userId.
       */
      public com.google.protobuf.ByteString getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       *
       *
       * <pre>
       * The following three ids are not persisted in BT and it's used for joining only!
       * </pre>
       *
       * <code>string user_id = 7;</code>
       *
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        userId_ = value;
        onChanged();
        return this;
      }
      /**
       *
       *
       * <pre>
       * The following three ids are not persisted in BT and it's used for joining only!
       * </pre>
       *
       * <code>string user_id = 7;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearUserId() {

        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       *
       *
       * <pre>
       * The following three ids are not persisted in BT and it's used for joining only!
       * </pre>
       *
       * <code>string user_id = 7;</code>
       *
       * @param value The bytes for userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserIdBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        userId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userName_ = "";
      /**
       * <code>string user_name = 11;</code>
       *
       * @return The userName.
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string user_name = 11;</code>
       *
       * @return The bytes for userName.
       */
      public com.google.protobuf.ByteString getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string user_name = 11;</code>
       *
       * @param value The userName to set.
       * @return This builder for chaining.
       */
      public Builder setUserName(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string user_name = 11;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearUserName() {

        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>string user_name = 11;</code>
       *
       * @param value The bytes for userName to set.
       * @return This builder for chaining.
       */
      public Builder setUserNameBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        userName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ghostId_ = "";
      /**
       * <code>string ghost_id = 21;</code>
       *
       * @return The ghostId.
       */
      public java.lang.String getGhostId() {
        java.lang.Object ref = ghostId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ghostId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ghost_id = 21;</code>
       *
       * @return The bytes for ghostId.
       */
      public com.google.protobuf.ByteString getGhostIdBytes() {
        java.lang.Object ref = ghostId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
          ghostId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ghost_id = 21;</code>
       *
       * @param value The ghostId to set.
       * @return This builder for chaining.
       */
      public Builder setGhostId(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        ghostId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ghost_id = 21;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearGhostId() {

        ghostId_ = getDefaultInstance().getGhostId();
        onChanged();
        return this;
      }
      /**
       * <code>string ghost_id = 21;</code>
       *
       * @param value The bytes for ghostId to set.
       * @return This builder for chaining.
       */
      public Builder setGhostIdBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        ghostId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object said_ = "";
      /**
       * <code>string said = 16;</code>
       *
       * @return The said.
       */
      public java.lang.String getSaid() {
        java.lang.Object ref = said_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          said_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string said = 16;</code>
       *
       * @return The bytes for said.
       */
      public com.google.protobuf.ByteString getSaidBytes() {
        java.lang.Object ref = said_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
          said_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string said = 16;</code>
       *
       * @param value The said to set.
       * @return This builder for chaining.
       */
      public Builder setSaid(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        said_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string said = 16;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearSaid() {

        said_ = getDefaultInstance().getSaid();
        onChanged();
        return this;
      }
      /**
       * <code>string said = 16;</code>
       *
       * @param value The bytes for said to set.
       * @return This builder for chaining.
       */
      public Builder setSaidBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        said_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<java.lang.String, java.lang.String> supplement_;

      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
          internalGetSupplement() {
        if (supplement_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              SupplementDefaultEntryHolder.defaultEntry);
        }
        return supplement_;
      }

      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
          internalGetMutableSupplement() {
        onChanged();
        ;
        if (supplement_ == null) {
          supplement_ =
              com.google.protobuf.MapField.newMapField(SupplementDefaultEntryHolder.defaultEntry);
        }
        if (!supplement_.isMutable()) {
          supplement_ = supplement_.copy();
        }
        return supplement_;
      }

      public int getSupplementCount() {
        return internalGetSupplement().getMap().size();
      }
      /** <code>map&lt;string, string&gt; supplement = 17;</code> */
      public boolean containsSupplement(java.lang.String key) {
        if (key == null) {
          throw new java.lang.NullPointerException();
        }
        return internalGetSupplement().getMap().containsKey(key);
      }
      /** Use {@link #getSupplementMap()} instead. */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getSupplement() {
        return getSupplementMap();
      }
      /** <code>map&lt;string, string&gt; supplement = 17;</code> */
      public java.util.Map<java.lang.String, java.lang.String> getSupplementMap() {
        return internalGetSupplement().getMap();
      }
      /** <code>map&lt;string, string&gt; supplement = 17;</code> */
      public java.lang.String getSupplementOrDefault(
          java.lang.String key, java.lang.String defaultValue) {
        if (key == null) {
          throw new java.lang.NullPointerException();
        }
        java.util.Map<java.lang.String, java.lang.String> map = internalGetSupplement().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /** <code>map&lt;string, string&gt; supplement = 17;</code> */
      public java.lang.String getSupplementOrThrow(java.lang.String key) {
        if (key == null) {
          throw new java.lang.NullPointerException();
        }
        java.util.Map<java.lang.String, java.lang.String> map = internalGetSupplement().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearSupplement() {
        internalGetMutableSupplement().getMutableMap().clear();
        return this;
      }
      /** <code>map&lt;string, string&gt; supplement = 17;</code> */
      public Builder removeSupplement(java.lang.String key) {
        if (key == null) {
          throw new java.lang.NullPointerException();
        }
        internalGetMutableSupplement().getMutableMap().remove(key);
        return this;
      }
      /** Use alternate mutation accessors instead. */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getMutableSupplement() {
        return internalGetMutableSupplement().getMutableMap();
      }
      /** <code>map&lt;string, string&gt; supplement = 17;</code> */
      public Builder putSupplement(java.lang.String key, java.lang.String value) {
        if (key == null) {
          throw new java.lang.NullPointerException();
        }
        if (value == null) {
          throw new java.lang.NullPointerException();
        }
        internalGetMutableSupplement().getMutableMap().put(key, value);
        return this;
      }
      /** <code>map&lt;string, string&gt; supplement = 17;</code> */
      public Builder putAllSupplement(java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableSupplement().getMutableMap().putAll(values);
        return this;
      }

      private com.google.protobuf.Internal.LongList installedHashedAppIds_ = emptyLongList();

      private void ensureInstalledHashedAppIdsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          installedHashedAppIds_ = mutableCopy(installedHashedAppIds_);
          bitField0_ |= 0x00000002;
        }
      }
      /**
       * <code>repeated int64 installed_hashed_app_ids = 23;</code>
       *
       * @return A list containing the installedHashedAppIds.
       */
      public java.util.List<java.lang.Long> getInstalledHashedAppIdsList() {
        return ((bitField0_ & 0x00000002) != 0)
            ? java.util.Collections.unmodifiableList(installedHashedAppIds_)
            : installedHashedAppIds_;
      }
      /**
       * <code>repeated int64 installed_hashed_app_ids = 23;</code>
       *
       * @return The count of installedHashedAppIds.
       */
      public int getInstalledHashedAppIdsCount() {
        return installedHashedAppIds_.size();
      }
      /**
       * <code>repeated int64 installed_hashed_app_ids = 23;</code>
       *
       * @param index The index of the element to return.
       * @return The installedHashedAppIds at the given index.
       */
      public long getInstalledHashedAppIds(int index) {
        return installedHashedAppIds_.getLong(index);
      }
      /**
       * <code>repeated int64 installed_hashed_app_ids = 23;</code>
       *
       * @param index The index to set the value at.
       * @param value The installedHashedAppIds to set.
       * @return This builder for chaining.
       */
      public Builder setInstalledHashedAppIds(int index, long value) {
        ensureInstalledHashedAppIdsIsMutable();
        installedHashedAppIds_.setLong(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 installed_hashed_app_ids = 23;</code>
       *
       * @param value The installedHashedAppIds to add.
       * @return This builder for chaining.
       */
      public Builder addInstalledHashedAppIds(long value) {
        ensureInstalledHashedAppIdsIsMutable();
        installedHashedAppIds_.addLong(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 installed_hashed_app_ids = 23;</code>
       *
       * @param values The installedHashedAppIds to add.
       * @return This builder for chaining.
       */
      public Builder addAllInstalledHashedAppIds(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureInstalledHashedAppIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(values, installedHashedAppIds_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 installed_hashed_app_ids = 23;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearInstalledHashedAppIds() {
        installedHashedAppIds_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }

      // @@protoc_insertion_point(builder_scope:com.snapchat.targeting.proto.UserProfile)
    }

    // @@protoc_insertion_point(class_scope:com.snapchat.targeting.proto.UserProfile)
    private static final com.snapchat.targeting.proto.UserProfileProto.UserProfile DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new com.snapchat.targeting.proto.UserProfileProto.UserProfile();
    }

    public static com.snapchat.targeting.proto.UserProfileProto.UserProfile getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserProfile> PARSER =
        new com.google.protobuf.AbstractParser<UserProfile>() {
          @java.lang.Override
          public UserProfile parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            return new UserProfile(input, extensionRegistry);
          }
        };

    public static com.google.protobuf.Parser<UserProfile> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserProfile> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.snapchat.targeting.proto.UserProfileProto.UserProfile getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }
  }

  public interface UserProfileHistoryOrBuilder
      extends
      // @@protoc_insertion_point(interface_extends:com.snapchat.targeting.proto.UserProfileHistory)
      com.google.protobuf.MessageOrBuilder {

    /**
     *
     *
     * <pre>
     * latest: demographics, app_profile, audience_segments, community
     * historical: attribution
     * </pre>
     *
     * <code>map&lt;string, .com.snapchat.targeting.proto.UserProfile&gt; profiles = 1;</code>
     */
    int getProfilesCount();
    /**
     *
     *
     * <pre>
     * latest: demographics, app_profile, audience_segments, community
     * historical: attribution
     * </pre>
     *
     * <code>map&lt;string, .com.snapchat.targeting.proto.UserProfile&gt; profiles = 1;</code>
     */
    boolean containsProfiles(java.lang.String key);
    /** Use {@link #getProfilesMap()} instead. */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.snapchat.targeting.proto.UserProfileProto.UserProfile>
        getProfiles();
    /**
     *
     *
     * <pre>
     * latest: demographics, app_profile, audience_segments, community
     * historical: attribution
     * </pre>
     *
     * <code>map&lt;string, .com.snapchat.targeting.proto.UserProfile&gt; profiles = 1;</code>
     */
    java.util.Map<java.lang.String, com.snapchat.targeting.proto.UserProfileProto.UserProfile>
        getProfilesMap();
    /**
     *
     *
     * <pre>
     * latest: demographics, app_profile, audience_segments, community
     * historical: attribution
     * </pre>
     *
     * <code>map&lt;string, .com.snapchat.targeting.proto.UserProfile&gt; profiles = 1;</code>
     */
    com.snapchat.targeting.proto.UserProfileProto.UserProfile getProfilesOrDefault(
        java.lang.String key,
        com.snapchat.targeting.proto.UserProfileProto.UserProfile defaultValue);
    /**
     *
     *
     * <pre>
     * latest: demographics, app_profile, audience_segments, community
     * historical: attribution
     * </pre>
     *
     * <code>map&lt;string, .com.snapchat.targeting.proto.UserProfile&gt; profiles = 1;</code>
     */
    com.snapchat.targeting.proto.UserProfileProto.UserProfile getProfilesOrThrow(
        java.lang.String key);

    /**
     * <code>string user_id = 2;</code>
     *
     * @return The userId.
     */
    java.lang.String getUserId();
    /**
     * <code>string user_id = 2;</code>
     *
     * @return The bytes for userId.
     */
    com.google.protobuf.ByteString getUserIdBytes();
  }
  /** Protobuf type {@code com.snapchat.targeting.proto.UserProfileHistory} */
  public static final class UserProfileHistory extends com.google.protobuf.GeneratedMessageV3
      implements
      // @@protoc_insertion_point(message_implements:com.snapchat.targeting.proto.UserProfileHistory)
      UserProfileHistoryOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use UserProfileHistory.newBuilder() to construct.
    private UserProfileHistory(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private UserProfileHistory() {
      userId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
      return new UserProfileHistory();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
      return this.unknownFields;
    }

    private UserProfileHistory(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10:
              {
                if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                  profiles_ =
                      com.google.protobuf.MapField.newMapField(
                          ProfilesDefaultEntryHolder.defaultEntry);
                  mutable_bitField0_ |= 0x00000001;
                }
                com.google.protobuf.MapEntry<
                        java.lang.String, com.snapchat.targeting.proto.UserProfileProto.UserProfile>
                    profiles__ =
                        input.readMessage(
                            ProfilesDefaultEntryHolder.defaultEntry.getParserForType(),
                            extensionRegistry);
                profiles_.getMutableMap().put(profiles__.getKey(), profiles__.getValue());
                break;
              }
            case 18:
              {
                java.lang.String s = input.readStringRequireUtf8();

                userId_ = s;
                break;
              }
            default:
              {
                if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.snapchat.targeting.proto.UserProfileProto
          .internal_static_com_snapchat_targeting_proto_UserProfileHistory_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(int number) {
      switch (number) {
        case 1:
          return internalGetProfiles();
        default:
          throw new RuntimeException("Invalid map field number: " + number);
      }
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.snapchat.targeting.proto.UserProfileProto
          .internal_static_com_snapchat_targeting_proto_UserProfileHistory_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.snapchat.targeting.proto.UserProfileProto.UserProfileHistory.class,
              com.snapchat.targeting.proto.UserProfileProto.UserProfileHistory.Builder.class);
    }

    public static final int PROFILES_FIELD_NUMBER = 1;

    private static final class ProfilesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
              java.lang.String, com.snapchat.targeting.proto.UserProfileProto.UserProfile>
          defaultEntry =
              com.google.protobuf.MapEntry
                  .<java.lang.String, com.snapchat.targeting.proto.UserProfileProto.UserProfile>
                      newDefaultInstance(
                          com.snapchat.targeting.proto.UserProfileProto
                              .internal_static_com_snapchat_targeting_proto_UserProfileHistory_ProfilesEntry_descriptor,
                          com.google.protobuf.WireFormat.FieldType.STRING,
                          "",
                          com.google.protobuf.WireFormat.FieldType.MESSAGE,
                          com.snapchat.targeting.proto.UserProfileProto.UserProfile
                              .getDefaultInstance());
    }

    private com.google.protobuf.MapField<
            java.lang.String, com.snapchat.targeting.proto.UserProfileProto.UserProfile>
        profiles_;

    private com.google.protobuf.MapField<
            java.lang.String, com.snapchat.targeting.proto.UserProfileProto.UserProfile>
        internalGetProfiles() {
      if (profiles_ == null) {
        return com.google.protobuf.MapField.emptyMapField(ProfilesDefaultEntryHolder.defaultEntry);
      }
      return profiles_;
    }

    public int getProfilesCount() {
      return internalGetProfiles().getMap().size();
    }
    /**
     *
     *
     * <pre>
     * latest: demographics, app_profile, audience_segments, community
     * historical: attribution
     * </pre>
     *
     * <code>map&lt;string, .com.snapchat.targeting.proto.UserProfile&gt; profiles = 1;</code>
     */
    public boolean containsProfiles(java.lang.String key) {
      if (key == null) {
        throw new java.lang.NullPointerException();
      }
      return internalGetProfiles().getMap().containsKey(key);
    }
    /** Use {@link #getProfilesMap()} instead. */
    @java.lang.Deprecated
    public java.util.Map<
            java.lang.String, com.snapchat.targeting.proto.UserProfileProto.UserProfile>
        getProfiles() {
      return getProfilesMap();
    }
    /**
     *
     *
     * <pre>
     * latest: demographics, app_profile, audience_segments, community
     * historical: attribution
     * </pre>
     *
     * <code>map&lt;string, .com.snapchat.targeting.proto.UserProfile&gt; profiles = 1;</code>
     */
    public java.util.Map<
            java.lang.String, com.snapchat.targeting.proto.UserProfileProto.UserProfile>
        getProfilesMap() {
      return internalGetProfiles().getMap();
    }
    /**
     *
     *
     * <pre>
     * latest: demographics, app_profile, audience_segments, community
     * historical: attribution
     * </pre>
     *
     * <code>map&lt;string, .com.snapchat.targeting.proto.UserProfile&gt; profiles = 1;</code>
     */
    public com.snapchat.targeting.proto.UserProfileProto.UserProfile getProfilesOrDefault(
        java.lang.String key,
        com.snapchat.targeting.proto.UserProfileProto.UserProfile defaultValue) {
      if (key == null) {
        throw new java.lang.NullPointerException();
      }
      java.util.Map<java.lang.String, com.snapchat.targeting.proto.UserProfileProto.UserProfile>
          map = internalGetProfiles().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     *
     *
     * <pre>
     * latest: demographics, app_profile, audience_segments, community
     * historical: attribution
     * </pre>
     *
     * <code>map&lt;string, .com.snapchat.targeting.proto.UserProfile&gt; profiles = 1;</code>
     */
    public com.snapchat.targeting.proto.UserProfileProto.UserProfile getProfilesOrThrow(
        java.lang.String key) {
      if (key == null) {
        throw new java.lang.NullPointerException();
      }
      java.util.Map<java.lang.String, com.snapchat.targeting.proto.UserProfileProto.UserProfile>
          map = internalGetProfiles().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int USER_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object userId_;
    /**
     * <code>string user_id = 2;</code>
     *
     * @return The userId.
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <code>string user_id = 2;</code>
     *
     * @return The bytes for userId.
     */
    public com.google.protobuf.ByteString getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3.serializeStringMapTo(
          output, internalGetProfiles(), ProfilesDefaultEntryHolder.defaultEntry, 1);
      if (!getUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<
              java.lang.String, com.snapchat.targeting.proto.UserProfileProto.UserProfile>
          entry : internalGetProfiles().getMap().entrySet()) {
        com.google.protobuf.MapEntry<
                java.lang.String, com.snapchat.targeting.proto.UserProfileProto.UserProfile>
            profiles__ =
                ProfilesDefaultEntryHolder.defaultEntry
                    .newBuilderForType()
                    .setKey(entry.getKey())
                    .setValue(entry.getValue())
                    .build();
        size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, profiles__);
      }
      if (!getUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof com.snapchat.targeting.proto.UserProfileProto.UserProfileHistory)) {
        return super.equals(obj);
      }
      com.snapchat.targeting.proto.UserProfileProto.UserProfileHistory other =
          (com.snapchat.targeting.proto.UserProfileProto.UserProfileHistory) obj;

      if (!internalGetProfiles().equals(other.internalGetProfiles())) return false;
      if (!getUserId().equals(other.getUserId())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetProfiles().getMap().isEmpty()) {
        hash = (37 * hash) + PROFILES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetProfiles().hashCode();
      }
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.snapchat.targeting.proto.UserProfileProto.UserProfileHistory parseFrom(
        java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.snapchat.targeting.proto.UserProfileProto.UserProfileHistory parseFrom(
        java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.snapchat.targeting.proto.UserProfileProto.UserProfileHistory parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.snapchat.targeting.proto.UserProfileProto.UserProfileHistory parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.snapchat.targeting.proto.UserProfileProto.UserProfileHistory parseFrom(
        byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.snapchat.targeting.proto.UserProfileProto.UserProfileHistory parseFrom(
        byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.snapchat.targeting.proto.UserProfileProto.UserProfileHistory parseFrom(
        java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.snapchat.targeting.proto.UserProfileProto.UserProfileHistory parseFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static com.snapchat.targeting.proto.UserProfileProto.UserProfileHistory
        parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static com.snapchat.targeting.proto.UserProfileProto.UserProfileHistory
        parseDelimitedFrom(
            java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static com.snapchat.targeting.proto.UserProfileProto.UserProfileHistory parseFrom(
        com.google.protobuf.CodedInputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.snapchat.targeting.proto.UserProfileProto.UserProfileHistory parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
          PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(
        com.snapchat.targeting.proto.UserProfileProto.UserProfileHistory prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /** Protobuf type {@code com.snapchat.targeting.proto.UserProfileHistory} */
    public static final class Builder
        extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
        implements
        // @@protoc_insertion_point(builder_implements:com.snapchat.targeting.proto.UserProfileHistory)
        com.snapchat.targeting.proto.UserProfileProto.UserProfileHistoryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.snapchat.targeting.proto.UserProfileProto
            .internal_static_com_snapchat_targeting_proto_UserProfileHistory_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(int number) {
        switch (number) {
          case 1:
            return internalGetProfiles();
          default:
            throw new RuntimeException("Invalid map field number: " + number);
        }
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(int number) {
        switch (number) {
          case 1:
            return internalGetMutableProfiles();
          default:
            throw new RuntimeException("Invalid map field number: " + number);
        }
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.snapchat.targeting.proto.UserProfileProto
            .internal_static_com_snapchat_targeting_proto_UserProfileHistory_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.snapchat.targeting.proto.UserProfileProto.UserProfileHistory.class,
                com.snapchat.targeting.proto.UserProfileProto.UserProfileHistory.Builder.class);
      }

      // Construct using
      // com.snapchat.targeting.proto.UserProfileProto.UserProfileHistory.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {}
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        internalGetMutableProfiles().clear();
        userId_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return com.snapchat.targeting.proto.UserProfileProto
            .internal_static_com_snapchat_targeting_proto_UserProfileHistory_descriptor;
      }

      @java.lang.Override
      public com.snapchat.targeting.proto.UserProfileProto.UserProfileHistory
          getDefaultInstanceForType() {
        return com.snapchat.targeting.proto.UserProfileProto.UserProfileHistory
            .getDefaultInstance();
      }

      @java.lang.Override
      public com.snapchat.targeting.proto.UserProfileProto.UserProfileHistory build() {
        com.snapchat.targeting.proto.UserProfileProto.UserProfileHistory result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.snapchat.targeting.proto.UserProfileProto.UserProfileHistory buildPartial() {
        com.snapchat.targeting.proto.UserProfileProto.UserProfileHistory result =
            new com.snapchat.targeting.proto.UserProfileProto.UserProfileHistory(this);
        int from_bitField0_ = bitField0_;
        result.profiles_ = internalGetProfiles();
        result.profiles_.makeImmutable();
        result.userId_ = userId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index,
          java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.snapchat.targeting.proto.UserProfileProto.UserProfileHistory) {
          return mergeFrom(
              (com.snapchat.targeting.proto.UserProfileProto.UserProfileHistory) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(
          com.snapchat.targeting.proto.UserProfileProto.UserProfileHistory other) {
        if (other
            == com.snapchat.targeting.proto.UserProfileProto.UserProfileHistory
                .getDefaultInstance()) return this;
        internalGetMutableProfiles().mergeFrom(other.internalGetProfiles());
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.snapchat.targeting.proto.UserProfileProto.UserProfileHistory parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage =
              (com.snapchat.targeting.proto.UserProfileProto.UserProfileHistory)
                  e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int bitField0_;

      private com.google.protobuf.MapField<
              java.lang.String, com.snapchat.targeting.proto.UserProfileProto.UserProfile>
          profiles_;

      private com.google.protobuf.MapField<
              java.lang.String, com.snapchat.targeting.proto.UserProfileProto.UserProfile>
          internalGetProfiles() {
        if (profiles_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ProfilesDefaultEntryHolder.defaultEntry);
        }
        return profiles_;
      }

      private com.google.protobuf.MapField<
              java.lang.String, com.snapchat.targeting.proto.UserProfileProto.UserProfile>
          internalGetMutableProfiles() {
        onChanged();
        ;
        if (profiles_ == null) {
          profiles_ =
              com.google.protobuf.MapField.newMapField(ProfilesDefaultEntryHolder.defaultEntry);
        }
        if (!profiles_.isMutable()) {
          profiles_ = profiles_.copy();
        }
        return profiles_;
      }

      public int getProfilesCount() {
        return internalGetProfiles().getMap().size();
      }
      /**
       *
       *
       * <pre>
       * latest: demographics, app_profile, audience_segments, community
       * historical: attribution
       * </pre>
       *
       * <code>map&lt;string, .com.snapchat.targeting.proto.UserProfile&gt; profiles = 1;</code>
       */
      public boolean containsProfiles(java.lang.String key) {
        if (key == null) {
          throw new java.lang.NullPointerException();
        }
        return internalGetProfiles().getMap().containsKey(key);
      }
      /** Use {@link #getProfilesMap()} instead. */
      @java.lang.Deprecated
      public java.util.Map<
              java.lang.String, com.snapchat.targeting.proto.UserProfileProto.UserProfile>
          getProfiles() {
        return getProfilesMap();
      }
      /**
       *
       *
       * <pre>
       * latest: demographics, app_profile, audience_segments, community
       * historical: attribution
       * </pre>
       *
       * <code>map&lt;string, .com.snapchat.targeting.proto.UserProfile&gt; profiles = 1;</code>
       */
      public java.util.Map<
              java.lang.String, com.snapchat.targeting.proto.UserProfileProto.UserProfile>
          getProfilesMap() {
        return internalGetProfiles().getMap();
      }
      /**
       *
       *
       * <pre>
       * latest: demographics, app_profile, audience_segments, community
       * historical: attribution
       * </pre>
       *
       * <code>map&lt;string, .com.snapchat.targeting.proto.UserProfile&gt; profiles = 1;</code>
       */
      public com.snapchat.targeting.proto.UserProfileProto.UserProfile getProfilesOrDefault(
          java.lang.String key,
          com.snapchat.targeting.proto.UserProfileProto.UserProfile defaultValue) {
        if (key == null) {
          throw new java.lang.NullPointerException();
        }
        java.util.Map<java.lang.String, com.snapchat.targeting.proto.UserProfileProto.UserProfile>
            map = internalGetProfiles().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       *
       *
       * <pre>
       * latest: demographics, app_profile, audience_segments, community
       * historical: attribution
       * </pre>
       *
       * <code>map&lt;string, .com.snapchat.targeting.proto.UserProfile&gt; profiles = 1;</code>
       */
      public com.snapchat.targeting.proto.UserProfileProto.UserProfile getProfilesOrThrow(
          java.lang.String key) {
        if (key == null) {
          throw new java.lang.NullPointerException();
        }
        java.util.Map<java.lang.String, com.snapchat.targeting.proto.UserProfileProto.UserProfile>
            map = internalGetProfiles().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearProfiles() {
        internalGetMutableProfiles().getMutableMap().clear();
        return this;
      }
      /**
       *
       *
       * <pre>
       * latest: demographics, app_profile, audience_segments, community
       * historical: attribution
       * </pre>
       *
       * <code>map&lt;string, .com.snapchat.targeting.proto.UserProfile&gt; profiles = 1;</code>
       */
      public Builder removeProfiles(java.lang.String key) {
        if (key == null) {
          throw new java.lang.NullPointerException();
        }
        internalGetMutableProfiles().getMutableMap().remove(key);
        return this;
      }
      /** Use alternate mutation accessors instead. */
      @java.lang.Deprecated
      public java.util.Map<
              java.lang.String, com.snapchat.targeting.proto.UserProfileProto.UserProfile>
          getMutableProfiles() {
        return internalGetMutableProfiles().getMutableMap();
      }
      /**
       *
       *
       * <pre>
       * latest: demographics, app_profile, audience_segments, community
       * historical: attribution
       * </pre>
       *
       * <code>map&lt;string, .com.snapchat.targeting.proto.UserProfile&gt; profiles = 1;</code>
       */
      public Builder putProfiles(
          java.lang.String key, com.snapchat.targeting.proto.UserProfileProto.UserProfile value) {
        if (key == null) {
          throw new java.lang.NullPointerException();
        }
        if (value == null) {
          throw new java.lang.NullPointerException();
        }
        internalGetMutableProfiles().getMutableMap().put(key, value);
        return this;
      }
      /**
       *
       *
       * <pre>
       * latest: demographics, app_profile, audience_segments, community
       * historical: attribution
       * </pre>
       *
       * <code>map&lt;string, .com.snapchat.targeting.proto.UserProfile&gt; profiles = 1;</code>
       */
      public Builder putAllProfiles(
          java.util.Map<java.lang.String, com.snapchat.targeting.proto.UserProfileProto.UserProfile>
              values) {
        internalGetMutableProfiles().getMutableMap().putAll(values);
        return this;
      }

      private java.lang.Object userId_ = "";
      /**
       * <code>string user_id = 2;</code>
       *
       * @return The userId.
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string user_id = 2;</code>
       *
       * @return The bytes for userId.
       */
      public com.google.protobuf.ByteString getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string user_id = 2;</code>
       *
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string user_id = 2;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearUserId() {

        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>string user_id = 2;</code>
       *
       * @param value The bytes for userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserIdBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        userId_ = value;
        onChanged();
        return this;
      }

      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }

      // @@protoc_insertion_point(builder_scope:com.snapchat.targeting.proto.UserProfileHistory)
    }

    // @@protoc_insertion_point(class_scope:com.snapchat.targeting.proto.UserProfileHistory)
    private static final com.snapchat.targeting.proto.UserProfileProto.UserProfileHistory
        DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new com.snapchat.targeting.proto.UserProfileProto.UserProfileHistory();
    }

    public static com.snapchat.targeting.proto.UserProfileProto.UserProfileHistory
        getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserProfileHistory> PARSER =
        new com.google.protobuf.AbstractParser<UserProfileHistory>() {
          @java.lang.Override
          public UserProfileHistory parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            return new UserProfileHistory(input, extensionRegistry);
          }
        };

    public static com.google.protobuf.Parser<UserProfileHistory> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserProfileHistory> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.snapchat.targeting.proto.UserProfileProto.UserProfileHistory
        getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }
  }

  private static final com.google.protobuf.Descriptors.Descriptor
      internal_static_com_snapchat_targeting_proto_UserProfile_descriptor;
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_snapchat_targeting_proto_UserProfile_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
      internal_static_com_snapchat_targeting_proto_UserProfile_SupplementEntry_descriptor;
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_snapchat_targeting_proto_UserProfile_SupplementEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
      internal_static_com_snapchat_targeting_proto_UserProfileHistory_descriptor;
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_snapchat_targeting_proto_UserProfileHistory_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
      internal_static_com_snapchat_targeting_proto_UserProfileHistory_ProfilesEntry_descriptor;
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_snapchat_targeting_proto_UserProfileHistory_ProfilesEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n\022user_profile.proto\022\034com.snapchat.targe"
          + "ting.proto\"\226\002\n\013UserProfile\022\037\n\027latest_tim"
          + "estamp_millis\030\010 \001(\003\022\017\n\007user_id\030\007 \001(\t\022\021\n\t"
          + "user_name\030\013 \001(\t\022\020\n\010ghost_id\030\025 \001(\t\022\014\n\004sai"
          + "d\030\020 \001(\t\022M\n\nsupplement\030\021 \003(\01329.com.snapch"
          + "at.targeting.proto.UserProfile.Supplemen"
          + "tEntry\022 \n\030installed_hashed_app_ids\030\027 \003(\003"
          + "\0321\n\017SupplementEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005valu"
          + "e\030\002 \001(\t:\0028\001\"\323\001\n\022UserProfileHistory\022P\n\010pr"
          + "ofiles\030\001 \003(\0132>.com.snapchat.targeting.pr"
          + "oto.UserProfileHistory.ProfilesEntry\022\017\n\007"
          + "user_id\030\002 \001(\t\032Z\n\rProfilesEntry\022\013\n\003key\030\001 "
          + "\001(\t\0228\n\005value\030\002 \001(\0132).com.snapchat.target"
          + "ing.proto.UserProfile:\0028\001B\022B\020UserProfile"
          + "Protob\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[] {});
    internal_static_com_snapchat_targeting_proto_UserProfile_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_com_snapchat_targeting_proto_UserProfile_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_com_snapchat_targeting_proto_UserProfile_descriptor,
            new java.lang.String[] {
              "LatestTimestampMillis",
              "UserId",
              "UserName",
              "GhostId",
              "Said",
              "Supplement",
              "InstalledHashedAppIds",
            });
    internal_static_com_snapchat_targeting_proto_UserProfile_SupplementEntry_descriptor =
        internal_static_com_snapchat_targeting_proto_UserProfile_descriptor.getNestedTypes().get(0);
    internal_static_com_snapchat_targeting_proto_UserProfile_SupplementEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_com_snapchat_targeting_proto_UserProfile_SupplementEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_com_snapchat_targeting_proto_UserProfileHistory_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_com_snapchat_targeting_proto_UserProfileHistory_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_com_snapchat_targeting_proto_UserProfileHistory_descriptor,
            new java.lang.String[] {
              "Profiles", "UserId",
            });
    internal_static_com_snapchat_targeting_proto_UserProfileHistory_ProfilesEntry_descriptor =
        internal_static_com_snapchat_targeting_proto_UserProfileHistory_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_com_snapchat_targeting_proto_UserProfileHistory_ProfilesEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_com_snapchat_targeting_proto_UserProfileHistory_ProfilesEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
